name: Test and Build Rust

on:
  push:
    # Enable when testing release infrastructure on a branch.
    branches:
    - build
    tags:
    - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  publish:
    name: Publish to crates.io
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      RUSTFLAGS: --allow unknown-lints --deny warnings
    steps:
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
      - uses: actions/checkout@v4
      - uses: katyo/publish-crates@v2
        with:
          registry-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}
          dry-run: ${{ !startsWith(github.ref, 'refs/tags/') }}

